@apiUrl = http://localhost:3030   

#@token = {{$dotenv TOKEN}}
### GET ALL
GET {{apiUrl}}/orders/
### GET BY ID
GET {{apiUrl}}/orders/65c34806d7ee2f95f3f61ccd
#Authorization: Bearer {{token}}

### NEW ORDER
POST {{apiUrl}}/orders
Content-Type: application/json

{
    "orderNumber": "delete me"
}

### PATCH ORDER

PATCH {{apiUrl}}/orders/65c345d944e759f300d08e22
Content-Type: application/json
#Authorization: Bearer {{token}}

{
    "orderNumber": "new reee numba"
}

### DELETE ORDER

DELETE {{apiUrl}}/orders/65ae3256846d9436453ce80b
#Authorization: Bearer {{token}}

###