@apiUrl = http://localhost:3030   

#@token = {{$dotenv TOKEN}}
###
GET {{apiUrl}}

###
GET {{apiUrl}}/id
#Authorization: Bearer {{token}}

### Logga in på /users/login
POST {{apiUrl}}/orders
Content-Type: application/json

{
    "orderNumber": "test"
}

### skapa ny användare
POST {{apiUrl}}/orders
Content-Type: application/json

{
    "orderNumber": "test"
}


### 
PATCH {{apiUrl}}/id
#Authorization: Bearer {{token}}
Content-Type: application/json

{
    
}

###
DELETE {{apiUrl}}/id
#Authorization: Bearer {{token}}

###