@apiUrl = http://localhost:3030   

@token = {{$dotenv TOKEN}}
### GET ALL
GET {{apiUrl}}/orders/
### GET BY ID
GET {{apiUrl}}/orders/myorders/65ce1fd30b994ec7411b68d5
Authorization: Bearer {{token}}

### GET ORDERS FOR LOGGED-IN USER
GET {{apiUrl}}/orders/myorders
Authorization: Bearer {{token}}
#/* TOKEN GENERATOR FOR TESTING USER ID
#http://localhost:3030/orders/generate-token to get ur token which you add to HTTP auth bearer
#*/

###Get token from above link and add to authorization for testing purposes! Also change userId in generator...
POST http://localhost:3030/orders
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "orderNumber": "new test",
  "product": "donny bump",
  "quantity": 2,
  "totalPrice": 50
}


### PATCH ORDER

PATCH http://localhost:3030/orders/65ce1d548a68f23529947b45
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "orderNumber": "123456",
  "product": "Updated 2",
  "quantity": 5,
  "totalPrice": 50.99
}

### DELETE ORDER

DELETE {{apiUrl}}/orders/65ce1d548a68f23529947b45
Authorization: Bearer {{token}}

###